name: Track YouTube iOS Version

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:     # Allow manual run

jobs:
  check-youtube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest YouTube version from App Store
        id: yt
        run: |
          latest=$(curl -s "https://itunes.apple.com/lookup?id=544007664" | jq -r '.results[0].version')
          echo "latest=$latest" >> $GITHUB_ENV
          echo "Latest version: $latest"

      - name: Check stored version
        id: compare
        run: |
          if [ -f last_version.txt ]; then
            stored=$(cat last_version.txt)
          else
            stored="none"
          fi
          echo "Stored version: $stored"
          echo "stored=$stored" >> $GITHUB_ENV

      - name: Update version if changed
        if: env.latest != env.stored
        run: |
          echo "${{ env.latest }}" > last_version.txt
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add last_version.txt
          git commit -m "YouTube iOS updated to ${{ env.latest }}"
          git push
